### ISSUE TITLE
Project / Stack / Workflow

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v9-bears-team-11#5]
@shimphillip and @paulywill decided on:

- [ x] Project - sound generator / something that create sample/beats/piano audio | perhaps ability for users to record to mp3 or  generate the code of audio

- [ x ] Stack - combination of Gatsby.js / Web Audio api

- [ x ] Workflow - Wednesday evening meetings / Discord / VS Code Live share / github workflow?

**Comment by ghost** [comment]
Is this a question that I should answer or something we come up with an answer to together?

**Comment by paulywill** [comment]
> Is this a question that I should answer or something we come up with an answer to together?

Was just tracking some of the things we talked about. Sorry, I should have not used that `question` label.
